### PR TITLE
feat(usability): Attempt for easier usability

### PR DESCRIPTION
**Pull request by zigzagcai**
## Motivation

Improve usability for InternEvo framework to facilitate integration of third-party or user-defined models.

## Modification

- Optimize checkpoint load/save logic
  - provide unified logic and interface for loading (via [load_hf_weights](https://github.com/InternLM/InternEvo/blob/refactor_develop_for_usability/internlm/model/base_model.py#L15)) and saving (via [convert_internevo2hf_weights](https://github.com/InternLM/InternEvo/blob/refactor_develop_for_usability/internlm/model/base_model.py#L20)) huggingface checkpoint format
   - provide unified configuration for [load](https://github.com/InternLM/InternEvo/blob/refactor_develop_for_usability/configs/7B_sft.py#L31-L33)/[save ](https://github.com/InternLM/InternEvo/blob/refactor_develop_for_usability/configs/7B_sft.py#L25)hf ckpt
  - provide base abstract model class (via [BaseModel](https://github.com/InternLM/InternEvo/blob/refactor_develop_for_usability/internlm/model/base_model.py#L8-L27)) for all `modeling_xxx.py`
  - already support load/save hf weights for internlm/internlm2/llama2

- Optimized `trainer_builder.py`
  - more readable and self-documented

- Support third-party models to directly run with `tp/wp/isp` parallel mode and pack training, simply by setting `config.model.inject_info` and few lines of code changes.

Example of injection with huggingface InternLM2 to support `tp/wp/isp` parallel mode and pack training:

1.  code changes

```
+from internlm.core.context import ParallelMode
+from internlm.core.context import global_context as gpc
+from internlm.model.ops.attention import isp_flash_attn_varlen_func, isp_flash_attn_func
+from internlm.initialize.initialize_tensor import normal_, scaled_init_method_normal
+
 try:
     from transformers.generation.streamers import BaseStreamer
 except Exception:
@@ -411,6 +416,14 @@ class InternLM2FlashAttention2(InternLM2Attention):
 
         bsz, q_len, _ = hidden_states.size()
 
+        use_packed_dataset = gpc.config.data.get("use_packed_dataset", False)
+
+        if use_packed_dataset:
+            assert bsz == 1, "hidden_states should be packed into bsz=1 when use_packed_dataset=True"
+            cu_seqlens = gpc.config.data[f"cu_seqlens_data_rank{gpc.get_local_rank(ParallelMode.DATA)}"]
+            max_seqlen = gpc.config.data[f"max_seqlen_data_rank{gpc.get_local_rank(ParallelMode.DATA)}"]
+            position_ids = position_ids.unsqueeze(0)
+
         qkv_states = self.wqkv(hidden_states)
 
         qkv_states = rearrange(
@@ -473,9 +486,23 @@ class InternLM2FlashAttention2(InternLM2Attention):
             key_states = key_states.to(target_dtype)
             value_states = value_states.to(target_dtype)
 
-        attn_output = self._flash_attention_forward(
-            query_states, key_states, value_states, attention_mask, q_len, dropout=dropout_rate
-        )
+        if use_packed_dataset:
+            attn_output = isp_flash_attn_varlen_func(
+                query_states,
+                key_states,
+                value_states,
+                cu_seqlens,
+                cu_seqlens,
+                max_seqlen,
+                max_seqlen,
+                attention_dropout=dropout_rate,
+                softmax_scale=None,
+                causal=False,
+            )
+        else:
+            attn_output = isp_flash_attn_func(
+                query_states, key_states, value_states, attention_dropout=dropout_rate, softmax_scale=None, causal=False,
+            )
```

2. config changes

```
    inject_info=dict(
        inject=True,  # inject model or just check model
        interactive=False, # if inject mode is automatic or interactive
        modules=["embed", "linear", "norm"], # the modules to be injected
        reset_params=False, # reset parameters
        data_helper=True, # set cu_seqlens and max_seqlens in gpc
    ),
```

## BC-breaking (Optional)

None

## Use cases (Optional)

None

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by zigzagcai** [comment]
Done.

**Comment by zigzagcai** [comment]
Done and ready for merge.

**Comment by zigzagcai** [comment]
Done and ready for merge.

**Comment by zigzagcai** [comment]
Done.

**Comment by zigzagcai** [comment]
Done.

**Comment by zigzagcai** [comment]
Done.

**Comment by zigzagcai** [comment]
Done.

**Review by sunpengsdu — APPROVED** [review]

**Pull request merged**
